"""reimplement_notifications_and_nested_comments

Revision ID: e62c7e2255b7
Revises: fc3044d0fce1
Create Date: 2026-03-30 22:06:03.364227

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e62c7e2255b7'
down_revision: Union[str, Sequence[str], None] = 'fc3044d0fce1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
